#!/bin/zsh
# vim: ft=sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

systemctl enable betterlockscreen@$USER
yadm submodule update --init --recursive
