#! /bin/sh

scripts=$HOME/.scripts
win_gap=17

function pstart() {
  exact=("-x")
  cmd=$1
  prog=${@:2}
  prog_name=$2

  case "$cmd" in
    one)
      pgrep $exact $prog > /dev/null || $prog &
      ;;
    kill)
      pgrep $exact $prog | xargs kill; $prog &
      ;;
    any)
      $prog &
      ;;
    *)
      echo "pstart: bad sub-command `$cmd`"
      ;;
  esac
}

# $HOME/.scripts needs to be in path
# Should be added in .xprofile
pstart one sxhkd
pstart one $scripts/polybar/launch.sh
pstart one picom
pstart one nm-applet
pstart one dunst
pstart one dropbox start

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_radius				  10
bspc config border_width          2
bspc config window_gap            $win_gap
bspc config border_width				  2
bspc config normal_border_color		'#59546d'
bspc config active_border_color		'#3e8fb0'
bspc config focused_border_color	'#ea9a97'
bspc config presel_feedback_color	'#c4a7e7'

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config honor_size_hints      true
bspc config remove_unplugged_monirots true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a kicad desktop='^3'
bspc rule -a discord desktop='^5'
# bspc rule -a firefox desktop='^4'
bspc rule -a gtop state=floating center=true
