#!/bin/zsh
# vim: ft=sh

notification(){
# change the icon to whatever you want. Make sure your notification server 
# supports it and already configured.

# Now it will receive argument so the user can rename the radio title
# to whatever they want

	notify-send "Playing now: " "$@" --icon=media-tape
}

menu(){
	printf "1. Lofi Girl\n"
	printf "2. Chillhop\n"
	printf "3. Justice Ders\n"
	printf "4. Bless\n"
	printf "5. Radio Spinner\n"
	printf "6. SmoothChill"
}

main() {
	choice=$(menu | rofi -dmenu | cut -d. -f1)

	case $choice in
		1)
			notification "Lofi Girl ☕️🎶";
            URL="https://www.youtube.com/watch?v=5qap5aO4i9A"
			;;
		2)
			notification "Lofi Cafe ☕️🎶";
            URL="https://www.youtube.com/watch?v=fR9BUCk79-Y"
			;;
		3)
			notification "Justice Der ☕️🎶";
            URL="https://www.youtube.com/watch?v=mPymRFeTJa4"
			;;
		4)
			notification "Bless ☕️🎶";
            URL="https://www.youtube.com/watch?v=oJuP-4Hsvkg&list=PLj6InK1rZv-lso8hXN2TWr9HhlsAq6PIS"
			;;
		5)
			notification "Radio Spinner ☕️🎶";
            URL="https://live.radiospinner.com/lofi-hip-hop-64"
			;;
		6)
			notification "SmoothChill ☕️🎶";
            URL="https://media-ssl.musicradio.com/SmoothChill"
			;;
		*)
			exit 1
			;;
	esac
    # run mpv with args and selected url
    # added title arg to make sure the pkill command kills only this instance of mpv
    mpv --volume=60 --no-video --title="radio-mpv" $URL
}

pkill -f radio-mpv || main
